name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”„ Repositorydan kodni yuklash
        uses: actions/checkout@v4

      - name: ğŸ¯ Flutter SDK-ni oâ€˜rnatish
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x" # Flutterning soâ€˜nggi versiyasi

      - name: ğŸ“¦ Dependencylarni yuklash
        run: flutter pub get

      - name: ğŸ§ª Testlarni ishga tushirish
        run: flutter test

      - name: ğŸ—ï¸ APK faylini build qilish
        run: flutter build apk --release

      - name: ğŸ“¦ AAB faylini build qilish
        run: flutter build appbundle --release

      - name: ğŸ“¤ APK faylini saqlash
        uses: actions/upload-artifact@v4
        with:
          name: APK Build
          path: build/app/outputs/flutter-apk/app-release.apk
        
      - name: ğŸ“¤ AAB faylini saqlash
        uses: actions/upload-artifact@v4
        with:
          name: AAB Build
          path: build/app/outputs/bundle/release/app-release.aab
